server:
  port: 9090

#本地数据库
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/honey2024?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    username: "root"
#    password: "123456"

#远程数据库
spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/second-hand?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: "ywy"
    password: "zuzu1313@@"
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB #控制上传文件大小

ip: 47.236.125.77






