server:
  port: 9090

#本地数据库
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/secondhand?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
#    username: "root"
#    password: "112333"

#远程数据库
spring:
  datasource:
    url: jdbc:mysql://${ip}:3306/secondhand?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: "root"
    password: "123!@#qweQWEmysql"
    hikari:
      max-lifetime: 30000
  servlet:
    multipart:
      max-request-size: 5MB
      max-file-size: 5MB #控制上传文件大小

  mail:
    host: smtp.qq.com
    port: 587
    username: 1029807850@qq.com
    password: abgigruefebsbbai
    from: 1029807850@qq.com
    nickname: "广应科二手易物平台"

    properties:
      mail:
        smtp:
          starttls:
            enable: true

ip: 47.115.49.214

myapp:
  global:
    staticVar:
      url: "http://${ip}:9091/login"
      ip: ${ip}








