server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/honey2024?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: "root"
    password: "123456"

